baseURL = "https://birdfly.land"
disableLanguages = []
disqusShortname = "birdfly"
paginate = "6"
summaryLength = "10"
#theme = "educenter-hugo-birdfly"
title = "Bird | Fly over Land"
defaultContentLanguage = "cn"
#[Languages.en]
#contentDir = "content/english"
#copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
#home = "Home"
#languageCode = "en-us"
#languageName = "En"
#weight = 1
[Languages.cn]
contentDir = "content/chinese"
copyright = "Copyright &copy; 2020 Tensor CHEN 保留所有权利"
home = "主页"
languageCode = "zh-cn"
languageName = "中文"
weight = 1
[[menu.footer]]
URL = "research"
name = "research"
weight = 1
[[menu.footer]]
URL = "scholarship"
name = "scholarship"
weight = 2
[[menu.footer]]
URL = "event"
name = "event"
weight = 3
[[menu.footer]]
URL = "notice"
name = "notice"
weight = 4
[[menu.footer]]
URL = "teacher"
name = "teacher"
weight = 5
#[[menu.main]]
#URL = "event"
#name = "event"
#parent = "更多"
#weight = 1
#[[menu.main]]
#URL = "teacher"
#name = "teacher"
#parent = "更多"
#weight = 2
[[menu.main]]
URL = "notice"
name = "招聘"
#parent = "更多"
weight = 5
#[[menu.main]]
#URL = "scholarship"
#name = "scholarship"
#parent = "更多"
#weight = 4
#[[menu.main]]
#URL = "research"
#name = "research"
#parent = "更多"
#weight = 5
#[[menu.main]]
#URL = "contact"
#name = "联系"
#weight = 3
[[menu.main]]
URL = "blog"
name = "博客"
weight = 4
#[[menu.main]]
#hasChildren = true
#name = "更多"
#weight = 5
#[[menu.main]]
#URL = "course"
#name = "图书"
#weight = 2
#[[menu.main]]
#URL = "about"
#name = "关于"
#weight = 1
[params]
address = "中国，深圳市南山区"
author = "Chen Yixiao"
contact_form_action = "#"
description = "This is meta description"
email = "birdfly@birdfly.land"
google_analitycs_id = ""
logo = "https://res.cloudinary.com/diq9dilor/image/upload/v1594314740/birdfly/static/images/tensorchen.png"
mobile = "birdflyland"
top_header = true
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/animate/animate.css"
[[params.plugins.css]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "https://res.cloudinary.com/diq9dilor/raw/upload/v1594314741/birdfly/static/plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "https://res.cloudinary.com/diq9dilor/image/upload/v1594314740/birdfly/static/images/preloader.gif"
[params.subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/tensorchen"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/ge_niao"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/yiniaoge"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "https://github.com/tensorchen"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
